In [1]:
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt




np.random.seed(2)


In [2]:
dataset = pd.read_csv(r'C:\Users\Naman Bhoj\Desktop\Feb-April\in process 2021\cicn 3 FAKE JON naman\fake_job_postings.csv')

In [3]:
dataset

job_id                                              title  \
0           1                                   Marketing Intern   
1           2          Customer Service - Cloud Video Production   
2           3            Commissioning Machinery Assistant (CMA)   
3           4                  Account Executive - Washington DC   
4           5                                Bill Review Manager   
...       ...                                                ...   
17875   17876                   Account Director - Distribution    
17876   17877                                 Payroll Accountant   
17877   17878  Project Cost Control Staff Engineer - Cost Con...   
17878   17879                                   Graphic Designer   
17879   17880                         Web Application Developers   

                   location   department salary_range  \
0          US, NY, New York    Marketing          NaN   
1            NZ, , Auckland      Success          NaN   
2             US, IA, Wever          NaN          NaN   
3        US, DC, Washington        Sales          NaN   
4        US, FL, Fort Worth          NaN          NaN   
...                     ...          ...          ...   
17875       CA, ON, Toronto        Sales          NaN   
17876  US, PA, Philadelphia   Accounting          NaN   
17877       US, TX, Houston          NaN          NaN   
17878         NG, LA, Lagos          NaN          NaN   
17879     NZ, N, Wellington  Engineering          NaN   

                                         company_profile  \
0      We're Food52, and we've created a groundbreaki...   
1      90 Seconds, the worlds Cloud Video Production ...   
2      Valor Services provides Workforce Solutions th...   
3      Our passion for improving quality of life thro...   
4      SpotSource Solutions LLC is a Global Human Cap...   
...                                                  ...   
17875  Vend is looking for some awesome new talent to...   
17876  WebLinc is the e-commerce platform and service...   
17877  We Provide Full Time Permanent Positions for m...   
17878                                                NaN   
17879  Vend is looking for some awesome new talent to...   

                                             description  \
0      Food52, a fast-growing, James Beard Award-winn...   
1      Organised - Focused - Vibrant - Awesome!Do you...   
2      Our client, located in Houston, is actively se...   
3      THE COMPANY: ESRI – Environmental Systems Rese...   
4      JOB TITLE: Itemization Review ManagerLOCATION:...   
...                                                  ...   
17875  Just in case this is the first time you’ve vis...   
17876  The Payroll Accountant will focus primarily on...   
17877  Experienced Project Cost Control Staff Enginee...   
17878  Nemsia Studios is looking for an experienced v...   
17879  Who are we?Vend is an award winning web based ...   

                                            requirements  \
0      Experience with content management systems a m...   
1      What we expect from you:Your key responsibilit...   
2      Implement pre-commissioning and commissioning ...   
3      EDUCATION: Bachelor’s or Master’s in GIS, busi...   
4      QUALIFICATIONS:RN license in the State of Texa...   
...                                                  ...   
17875  To ace this role you:Will eat comprehensive St...   
17876  - B.A. or B.S. in Accounting- Desire to have f...   
17877  At least 12 years professional experience.Abil...   
17878  1. Must be fluent in the latest versions of Co...   
17879  We want to hear from you if:You have an in-dep...   

                                                benefits  telecommuting  \
0                                                    NaN              0   
1      What you will get from usThrough being part of...              0   
2                                                    NaN              0   
3      Our culture is anything but corpora

In [4]:
len(dataset)

17880

# combine text feature and make one single feature

In [5]:
dataset['text_feature']=dataset['title']+" " + dataset['department'] + " " + dataset['company_profile'] + " " + dataset['description'] + " " + dataset['requirements'] + " " + dataset['benefits'] + " " 

# the tab above shows huge data imbalance

In [6]:
dataset_text = dataset[['text_feature', 'fraudulent']]

In [7]:
dataset_text.isnull().sum()

text_feature    14095
fraudulent          0
dtype: int64

# drop null values

In [24]:
dataset_text['text_feature'].iloc[4]

"Account Executive - Sydney Sales Adthena is the UK’s leading competitive intelligence service for Google search advertisers. Adthena is loved by major brands and digital agencies alike and provides a great opportunity to work in the high growth adtech space. Our patent-pending technologies provide unparalleled accuracy for clients to understand their competitors’ keywords, budgets, spend, CPCs, Adcopy and more. We're profitable, fast growing and love what we do. Are you interested in a satisfying and financially rewarding role in a high growth technology company? You’ll work in a casual yet high energy environment alongside passionate people delivering the leading competitive intelligence solution to major global brands. With the continued rapid growth of digital marketing and PPC a huge opportunity exists to further expand the Adthena enterprise client base. We are seeking an experienced Account Executive to develop and close new business in enterprise accounts. A large opportunity e

In [8]:
dataset_text = dataset_text.dropna()

In [9]:
x_data = dataset_text.drop(['fraudulent'],axis = 1)
y_data = dataset_text['fraudulent']

In [10]:
y_data.value_counts()

0    3647
1     138
Name: fraudulent, dtype: int64

# tab above shows huge data imbalance

In [15]:
x_data['text_feature'] = x_data["text_feature"].str.lower()
x_data.head()


text_feature
1   customer service - cloud video production succ...
3   account executive - washington dc sales our pa...
6   head of content (m/f) androidpit founded in 20...
11  talent sourcer (6 months fixed-term contract) ...
14  account executive - sydney sales adthena is th...

# remove punctuations

In [16]:
import string
PUNCT_TO_REMOVE = string.punctuation
def remove_punctuation(text):
    """custom function to remove the punctuation"""
    return text.translate(str.maketrans('', '', PUNCT_TO_REMOVE))

x_data["text_feature"] = x_data["text_feature"].apply(lambda text: remove_punctuation(text))

x_data.head()

text_feature
1   customer service  cloud video production succe...
3   account executive  washington dc sales our pas...
6   head of content mf androidpit founded in 2009 ...
11  talent sourcer 6 months fixedterm contract hr ...
14  account executive  sydney sales adthena is the...

In [17]:
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords
STOPWORDS = set(stopwords.words('english'))
def remove_stopwords(text):
    """custom function to remove the stopwords"""
    return " ".join([word for word in str(text).split() if word not in STOPWORDS])

x_data["text_feature"] = x_data["text_feature"].apply(lambda text: remove_stopwords(text))



[nltk_data] Downloading package stopwords to C:\Users\Naman
[nltk_data]     Bhoj\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [18]:
x_data

text_feature
1      customer service cloud video production succes...
3      account executive washington dc sales passion ...
6      head content mf androidpit founded 2009 fonpit...
11     talent sourcer 6 months fixedterm contract hr ...
14     account executive sydney sales adthena uk’s le...
...                                                  ...
17853  call centercustomer service customer service c...
17865  portfolio development associate paris rest fra...
17872  product manager product development flite deli...
17875  account director distribution sales vend looki...
17876  payroll accountant accounting weblinc ecommerc...

[3785 rows x 1 columns]

In [19]:
from nltk.stem import WordNetLemmatizer
nltk.download('wordnet')
lemmatizer = WordNetLemmatizer()
def lemmatize_words(text):
    return " ".join([lemmatizer.lemmatize(word) for word in text.split()])

x_data["text_feature"] = x_data["text_feature"].apply(lambda text: lemmatize_words(text))

[nltk_data] Downloading package wordnet to C:\Users\Naman
[nltk_data]     Bhoj\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


In [20]:
from wordcloud import WordCloud

# below tab shows text contained when non fraudulent

In [21]:
# import matplotlib.pyplot as plt
# from wordcloud import WordCloud,STOPWORDS
# from nltk.stem import WordNetLemmatizer
# plt.figure(figsize = (20,20)) # Text that is not fraudulent(0)
# wc = WordCloud(width = 800 , height = 800 , max_words = 1000,background_color = 'white').generate(" ".join(dataset_text[dataset_text.fraudulent == 0].text_feature))
# plt.imshow(wc , interpolation = 'bilinear')

In [22]:
# import matplotlib.pyplot as plt
# from wordcloud import WordCloud,STOPWORDS
# from nltk.stem import WordNetLemmatizer
# plt.figure(figsize = (20,20)) # Text  fraudulent(1)
# wc = WordCloud(width = 800 , height = 800 , max_words = 1000,background_color = 'white').generate(" ".join(dataset_text[dataset_text.fraudulent == 1].text_feature))
# plt.imshow(wc , interpolation = 'bilinear')

In [23]:
x_data

text_feature
1      customer service cloud video production succes...
3      account executive washington dc sale passion i...
6      head content mf androidpit founded 2009 fonpit...
11     talent sourcer 6 month fixedterm contract hr w...
14     account executive sydney sale adthena uk’s lea...
...                                                  ...
17853  call centercustomer service customer service c...
17865  portfolio development associate paris rest fra...
17872  product manager product development flite deli...
17875  account director distribution sale vend lookin...
17876  payroll accountant accounting weblinc ecommerc...

[3785 rows x 1 columns]

In [24]:
import tensorflow as tf

from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

vocab_size = 100000
embedding_dim = 32
max_length = 500

training_size = 10000
#Tokenization

tokenizer = Tokenizer(num_words=vocab_size)
tokenizer.fit_on_texts(x_data['text_feature'].values)
word_index = tokenizer.word_index
print(len(word_index))


59606


In [25]:
X = tokenizer.texts_to_sequences(x_data['text_feature'].values)                         #Tokenize the dataset
X = pad_sequences(X, maxlen=max_length)     #Padding the dataset

print(y_data.shape)

(3785,)


In [26]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y_data, test_size = 0.20,random_state=2)

In [27]:
from sklearn.ensemble import RandomForestClassifier

In [28]:
rfc = RandomForestClassifier(n_estimators = 150)

# fit bilstm

In [29]:
X_train

array([[    0,     0,     0, ..., 58899,   515,   188],
       [    0,     0,     0, ...,    77,   636,  1445],
       [    0,     0,     0, ...,   774,    83,   170],
       ...,
       [    0,     0,     0, ...,    30,  1015,   103],
       [    0,     0,     0, ...,  1496,  1679,     4],
       [    0,     0,     0, ...,   974,   118,    11]])

In [30]:
rfc.fit(X_train,y_train)

RandomForestClassifier(n_estimators=150)

# tokenise

In [31]:
predict_rfc=rfc.predict(X_test)
predict_rfc = np.around(predict_rfc, decimals = 0)
predict_rfc

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,

In [32]:
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score
c_report=classification_report(y_test,predict_rfc,target_names = ['0','1'],digits = 5)
print(c_report)

              precision    recall  f1-score   support

           0    0.96667   1.00000   0.98305       725
           1    1.00000   0.21875   0.35897        32

    accuracy                        0.96697       757
   macro avg    0.98333   0.60938   0.67101       757
weighted avg    0.96808   0.96697   0.95667       757



In [33]:
from sklearn.metrics import confusion_matrix
cf=confusion_matrix(y_test,predict_rfc)
cf


array([[725,   0],
       [ 25,   7]], dtype=int64)

In [34]:
from sklearn import svm

sv = svm.SVC()

In [35]:
sv.fit(X_train,y_train)

SVC()

In [36]:
predict_sv=sv.predict(X_test)
predict_sv = np.around(predict_sv, decimals = 0)
predict_sv

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [37]:
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score
c_report=classification_report(y_test,predict_sv,target_names = ['0','1'],digits = 5)
print(c_report)

              precision    recall  f1-score   support

           0    0.95773   1.00000   0.97841       725
           1    0.00000   0.00000   0.00000        32

    accuracy                        0.95773       757
   macro avg    0.47886   0.50000   0.48920       757
weighted avg    0.91724   0.95773   0.93705       757



C:\Users\Naman Bhoj\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Naman Bhoj\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Naman Bhoj\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


# storing vectorized in to data frame

In [38]:
from sklearn.metrics import confusion_matrix
cf=confusion_matrix(y_test,predict_sv)
cf


array([[725,   0],
       [ 32,   0]], dtype=int64)